drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
/* DB실행 : ./h2.sh
   sql: int(4byte) 는 DB에서 bigint(8byte)
 */